namespace AiVM.Core;

public interface ISyscallHost
{
    string[] ProcessArgv();
    string ProcessEnvGet(string name);
    int TimeNowUnixMs();
    int TimeMonotonicMs();
    void TimeSleepMs(int ms);
    void ConsoleWriteErrLine(string text);
    void ConsoleWrite(string text);
    string ProcessCwd();
    void ConsolePrintLine(string text);
    void IoPrint(string text);
    void IoWrite(string text);
    string IoReadLine();
    string IoReadAllStdin();
    string IoReadFile(string path);
    bool IoFileExists(string path);
    bool IoPathExists(string path);
    void IoMakeDir(string path);
    void IoWriteFile(string path, string text);

    string FsReadFile(string path);
    bool FsFileExists(string path);
    string[] FsReadDir(string path);
    VmFsStat FsStat(string path);
    bool FsPathExists(string path);
    void FsWriteFile(string path, string text);
    void FsMakeDir(string path);
    int StrUtf8ByteCount(string text);
    string Platform();
    string Architecture();
    string OsVersion();
    string Runtime();

    int NetListen(VmNetworkState state, int port);
    int NetListenTls(VmNetworkState state, int port, string certPath, string keyPath);
    int NetAccept(VmNetworkState state, int listenerHandle);
    string NetReadHeaders(VmNetworkState state, int connectionHandle);
    bool NetWrite(VmNetworkState state, int connectionHandle, string text);
    void NetClose(VmNetworkState state, int handle);
    int NetTcpListen(VmNetworkState state, string host, int port);
    int NetTcpListenTls(VmNetworkState state, string host, int port, string certPath, string keyPath);
    int NetTcpConnect(VmNetworkState state, string host, int port);
    int NetTcpConnectTls(VmNetworkState state, string host, int port);
    int NetTcpConnectStart(VmNetworkState state, string host, int port);
    int NetTcpConnectTlsStart(VmNetworkState state, string host, int port);
    int NetTcpReadStart(VmNetworkState state, int connectionHandle, int maxBytes);
    int NetTcpWriteStart(VmNetworkState state, int connectionHandle, string data);
    int NetAsyncPoll(VmNetworkState state, int operationHandle);
    int NetAsyncAwait(VmNetworkState state, int operationHandle);
    bool NetAsyncCancel(VmNetworkState state, int operationHandle);
    int NetAsyncResultInt(VmNetworkState state, int operationHandle);
    string NetAsyncResultString(VmNetworkState state, int operationHandle);
    string NetAsyncError(VmNetworkState state, int operationHandle);
    int WorkerStart(VmNetworkState state, string taskName, string payload);
    int WorkerPoll(VmNetworkState state, int workerHandle);
    string WorkerResult(VmNetworkState state, int workerHandle);
    string WorkerError(VmNetworkState state, int workerHandle);
    bool WorkerCancel(VmNetworkState state, int workerHandle);
    void DebugEmit(string channel, string payload);
    string DebugMode();
    void DebugCaptureFrameBegin(int frameId, int width, int height);
    void DebugCaptureFrameEnd(int frameId);
    void DebugCaptureDraw(string op, string args);
    void DebugCaptureInput(string eventPayload);
    void DebugCaptureState(string key, string valuePayload);
    int DebugReplayLoad(VmNetworkState state, string path);
    string DebugReplayNext(VmNetworkState state, int handle);
    void DebugAssert(bool cond, string code, string message);
    bool DebugArtifactWrite(string path, string text);
    void DebugTraceAsync(int opId, string phase, string detail);
    int NetTcpAccept(VmNetworkState state, int listenerHandle);
    string NetTcpRead(VmNetworkState state, int connectionHandle, int maxBytes);
    int NetTcpWrite(VmNetworkState state, int connectionHandle, string data);
    int NetUdpBind(VmNetworkState state, string host, int port);
    VmUdpPacket NetUdpRecv(VmNetworkState state, int handle, int maxBytes);
    int NetUdpSend(VmNetworkState state, int handle, string host, int port, string data);
    int UiCreateWindow(string title, int width, int height);
    void UiBeginFrame(int windowHandle);
    void UiDrawRect(int windowHandle, int x, int y, int width, int height, string color);
    void UiDrawText(int windowHandle, int x, int y, string text, string color, int size);
    void UiDrawLine(int windowHandle, int x1, int y1, int x2, int y2, string color, int strokeWidth);
    void UiDrawEllipse(int windowHandle, int x, int y, int width, int height, string color);
    void UiDrawPath(int windowHandle, string path, string color, int strokeWidth);
    void UiDrawImage(int windowHandle, int x, int y, int width, int height, string rgbaBase64);
    void UiEndFrame(int windowHandle);
    VmUiEvent UiPollEvent(int windowHandle);
    void UiWaitFrame(int windowHandle);
    VmUiWindowSize UiGetWindowSize(int windowHandle);
    void UiPresent(int windowHandle);
    void UiCloseWindow(int windowHandle);
    string CryptoBase64Encode(string text);
    string CryptoBase64Decode(string text);
    string CryptoSha1(string text);
    string CryptoSha256(string text);
    string CryptoHmacSha256(string key, string text);
    string CryptoRandomBytes(int count);

    void StdoutWriteLine(string text);
    void ProcessExit(int code);
}
